### ISSUE TITLE
"Drag-n-Drop" Assets for Engine Rebranding

### ISSUE THREAD

**Issue by Starkium** [blazium-engine/blazium-assets#15]
Replace/Rename Godot/Redot assets in the "Drag-n-Drop Assets" folder to be Blazium assets

This folder was set up to identically match assets folder from the engine. 
Also, update the "image_dimensions.txt" file as you update individual assets. This will help act as a check list. 

This might be a little sticky as these assets need to pass when running through the linter.

**Comment by Norrox** [comment]
i think i just did all of these
